---
version: 1.0

config:
  csvFilename: results.csv
  sarifFilename: results.sarif
  parentDirectory: force-app/main/default/

rules:
  - name: field-should-have-a-description
    active: true
    priority: 2

  - name: object-should-have-a-description
    active: true
    priority: 2

  - name: field-description-minimum-length
    active: true
    priority: 2
    properties:
      - name: minimumLength
        value: 35
