---
version: 1.0

config:
  csvFilename: results.csv
  sarifFilename: results.sarif
  parentDirectory: force-app/main/default/

rules:
  - name: no-missing-description-on-fields
    active: true
    level: warning

  - name: no-missing-description-on-objects
    active: true
    level: warning

  - name: no-missing-description-on-flows
    active: true
    level: warning

  - name: no-missing-description-on-validation-rules
    active: true
    level: warning

  - name: description-min-length-on-fields
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: description-min-length-on-objects
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: description-min-length-on-flows
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: description-min-length-on-validation-rules
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: error-message-min-length-on-validation-rules
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: no-missing-prefix-on-metadata
    active: true
    level: warning
    options:
      - name: prefixes
        value: ACME_
      - name: types
        value: field, fieldSet, listView
      - name: exclude-namespaces
        value: FinServ__, et4ae5__

  - name: no-prefix-on-metadata
    active: true
    level: warning
    options:
      - name: prefixes
        value: ACME_, TEST_
      - name: types
        value: field, fieldSet, listView
      - name: exclude-namespaces
        value: FinServ__, et4ae5__

  - name: no-double-spaces-in-picklist-fields
    active: true
    level: error

  - name: no-double-spaces-in-value-sets
    active: true
    level: error
