---
version: 1.0

config:
  csvFilename: results.csv
  sarifFilename: results.sarif
  parentDirectory: force-app/main/default/

rules:
  - name: field-should-have-a-description
    active: true
    level: warning

  - name: object-should-have-a-description
    active: true
    level: warning

  - name: flow-should-have-a-description
    active: true
    level: warning

  - name: validation-rule-should-have-a-description
    active: true
    level: warning

  - name: field-description-minimum-length
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: object-description-minimum-length
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: flow-description-minimum-length
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: validation-rule-description-minimum-length
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: validation-rule-error-minimum-length
    active: true
    level: warning
    options:
      - name: minimumLength
        value: 100

  - name: metadata-should-have-prefix
    active: false
    level: warning
    options:
      - name: prefixes
        value: ACME_
      - name: types
        value: field, fieldSet, listView
      - name: exclude-namespaces
        value: FinServ__, et4ae5__

  - name: metadata-should-not-have-prefix
    active: false
    level: warning
    options:
      - name: prefixes
        value: ACME_, TEST_
      - name: types
        value: field, fieldSet, listView
      - name: exclude-namespaces
        value: FinServ__, et4ae5__

  - name: picklists-should-not-contain-double-spaces
    active: true
    level: error

  - name: value-set-should-not-contain-double-spaces
    active: true
    level: error
